---
apiVersion: v1
kind: Service
metadata:
  name: zmq-broker
  labels:
    run: zmq-broker
spec:
  ports:
  - port: 15554
    name: frontend_port
    protocol: TCP
  - port: 15555
    name: backend_port
    protocol: TCP
  type: NodePort
  selector:
    app: zmq-broker